const sectorOption = {
  'sec_basicmaterials': 'Basic Materials',
  'sec_communicationservices': 'Communication Services',
  'sec_consumercyclical': 'Consumer Cyclical',
  'sec_consumerdefensive': 'Consumer Defensive',
  'sec_energy': 'Energy',
  'sec_financial': 'Financial',
  'sec_healthcare': 'Healthcare',
  'sec_industrials': 'Industrials',
  'sec_realestate': 'Real Estate',
  'sec_technology': 'Technology',
  'sec_utilities': 'Utilities'
}

const industryOption = {
  'ind_advertisingagencies': 'Advertising Agencies',
  'ind_aerospacedefense': 'Aerospace & Defense',
  'ind_agriculturalinputs': 'Agricultural Inputs',
  'ind_airlines': 'Airlines',
  'ind_airportsairservices': 'Airports & Air Services',
  'ind_aluminum': 'Aluminum',
  'ind_apparelmanufacturing': 'Apparel Manufacturing',
  'ind_apparelretail': 'Apparel Retail',
  'ind_assetmanagement': 'Asset Management',
  'ind_automanufacturers': 'Auto Manufacturers',
  'ind_autoparts': 'Auto Parts',
  'ind_autotruckdealerships': 'Auto & Truck Dealerships',
  'ind_banksdiversified': 'Banks - Diversified',
  'ind_banksregional': 'Banks - Regional',
  'ind_beveragesbrewers': 'Beverages - Brewers',
  'ind_beveragesnonalcoholic': 'Beverages - Non-Alcoholic',
  'ind_beverageswineriesdistilleries': 'Beverages - Wineries & Distilleries',
  'ind_biotechnology': 'Biotechnology',
  'ind_broadcasting': 'Broadcasting',
  'ind_buildingmaterials': 'Building Materials',
  'ind_buildingproductsequipment': 'Building Products & Equipment',
  'ind_businessequipmentsupplies': 'Business Equipment & Supplies',
  'ind_capitalmarkets': 'Capital Markets',
  'ind_chemicals': 'Chemicals',
  'ind_closedendfunddebt': 'Closed-End Fund - Debt',
  'ind_closedendfundequity': 'Closed-End Fund - Equity',
  'ind_closedendfundforeign': 'Closed-End Fund - Foreign',
  'ind_cokingcoal': 'Coking Coal',
  'ind_communicationequipment': 'Communication Equipment',
  'ind_computerhardware': 'Computer Hardware',
  'ind_confectioners': 'Confectioners',
  'ind_conglomerates': 'Conglomerates',
  'ind_consultingservices': 'Consulting Services',
  'ind_consumerelectronics': 'Consumer Electronics',
  'ind_copper': 'Copper',
  'ind_creditservices': 'Credit Services',
  'ind_departmentstores': 'Department Stores',
  'ind_diagnosticsresearch': 'Diagnostics & Research',
  'ind_discountstores': 'Discount Stores',
  'ind_drugmanufacturersgeneral': 'Drug Manufacturers - General',
  'ind_drugmanufacturersspecialtygeneric': 'Drug Manufacturers - Specialty & Generic',
  'ind_educationtrainingservices': 'Education & Training Services',
  'ind_electricalequipmentparts': 'Electrical Equipment & Parts',
  'ind_electroniccomponents': 'Electronic Components',
  'ind_electronicgamingmultimedia': 'Electronic Gaming & Multimedia',
  'ind_electronicscomputerdistribution': 'Electronics & Computer Distribution',
  'ind_engineeringconstruction': 'Engineering & Construction',
  'ind_entertainment': 'Entertainment',
  'ind_exchangetradedfund': 'Exchange Traded Fund',
  'ind_farmheavyconstructionmachinery': 'Farm & Heavy Construction Machinery',
  'ind_farmproducts': 'Farm Products',
  'ind_financialconglomerates': 'Financial Conglomerates',
  'ind_financialdatastockexchanges': 'Financial Data & Stock Exchanges',
  'ind_fooddistribution': 'Food Distribution',
  'ind_footwearaccessories': 'Footwear & Accessories',
  'ind_furnishingsfixturesappliances': 'Furnishings, Fixtures & Appliances',
  'ind_gambling': 'Gambling',
  'ind_gold': 'Gold',
  'ind_grocerystores': 'Grocery Stores',
  'ind_healthcareplans': 'Healthcare Plans',
  'ind_healthinformationservices': 'Health Information Services',
  'ind_homeimprovementretail': 'Home Improvement Retail',
  'ind_householdpersonalproducts': 'Household & Personal Products',
  'ind_industrialdistribution': 'Industrial Distribution',
  'ind_informationtechnologyservices': 'Information Technology Services',
  'ind_infrastructureoperations': 'Infrastructure Operations',
  'ind_insurancebrokers': 'Insurance Brokers',
  'ind_insurancediversified': 'Insurance - Diversified',
  'ind_insurancelife': 'Insurance - Life',
  'ind_insurancepropertycasualty': 'Insurance - Property & Casualty',
  'ind_insurancereinsurance': 'Insurance - Reinsurance',
  'ind_insurancespecialty': 'Insurance - Specialty',
  'ind_integratedfreightlogistics': 'Integrated Freight & Logistics',
  'ind_internetcontentinformation': 'Internet Content & Information',
  'ind_internetretail': 'Internet Retail',
  'ind_leisure': 'Leisure',
  'ind_lodging': 'Lodging',
  'ind_lumberwoodproduction': 'Lumber & Wood Production',
  'ind_luxurygoods': 'Luxury Goods',
  'ind_marineshipping': 'Marine Shipping',
  'ind_medicalcarefacilities': 'Medical Care Facilities',
  'ind_medicaldevices': 'Medical Devices',
  'ind_medicaldistribution': 'Medical Distribution',
  'ind_medicalinstrumentssupplies': 'Medical Instruments & Supplies',
  'ind_metalfabrication': 'Metal Fabrication',
  'ind_mortgagefinance': 'Mortgage Finance',
  'ind_oilgasdrilling': 'Oil & Gas Drilling',
  'ind_oilgasep': 'Oil & Gas E&P',
  'ind_oilgasequipmentservices': 'Oil & Gas Equipment & Services',
  'ind_oilgasintegrated': 'Oil & Gas Integrated',
  'ind_oilgasmidstream': 'Oil & Gas Midstream',
  'ind_oilgasrefiningmarketing': 'Oil & Gas Refining & Marketing',
  'ind_otherindustrialmetalsmining': 'Other Industrial Metals & Mining',
  'ind_otherpreciousmetalsmining': 'Other Precious Metals & Mining',
  'ind_packagedfoods': 'Packaged Foods',
  'ind_packagingcontainers': 'Packaging & Containers',
  'ind_paperpaperproducts': 'Paper & Paper Products',
  'ind_personalservices': 'Personal Services',
  'ind_pharmaceuticalretailers': 'Pharmaceutical Retailers',
  'ind_pollutiontreatmentcontrols': 'Pollution & Treatment Controls',
  'ind_publishing': 'Publishing',
  'ind_railroads': 'Railroads',
  'ind_realestatedevelopment': 'Real Estate - Development',
  'ind_realestatediversified': 'Real Estate - Diversified',
  'ind_realestateservices': 'Real Estate Services',
  'ind_recreationalvehicles': 'Recreational Vehicles',
  'ind_reitdiversified': 'REIT - Diversified',
  'ind_reithealthcarefacilities': 'REIT - Healthcare Facilities',
  'ind_reithotelmotel': 'REIT - Hotel & Motel',
  'ind_reitindustrial': 'REIT - Industrial',
  'ind_reitmortgage': 'REIT - Mortgage',
  'ind_reitoffice': 'REIT - Office',
  'ind_reitresidential': 'REIT - Residential',
  'ind_reitretail': 'REIT - Retail',
  'ind_reitspecialty': 'REIT - Specialty',
  'ind_rentalleasingservices': 'Rental & Leasing Services',
  'ind_residentialconstruction': 'Residential Construction',
  'ind_resortscasinos': 'Resorts & Casinos',
  'ind_restaurants': 'Restaurants',
  'ind_scientifictechnicalinstruments': 'Scientific & Technical Instruments',
  'ind_securityprotectionservices': 'Security & Protection Services',
  'ind_semiconductorequipmentmaterials': 'Semiconductor Equipment & Materials',
  'ind_semiconductors': 'Semiconductors',
  'ind_shellcompanies': 'Shell Companies',
  'ind_silver': 'Silver',
  'ind_softwareapplication': 'Software - Application',
  'ind_softwareinfrastructure': 'Software - Infrastructure',
  'ind_solar': 'Solar',
  'ind_specialtybusinessservices': 'Specialty Business Services',
  'ind_specialtychemicals': 'Specialty Chemicals',
  'ind_specialtyindustrialmachinery': 'Specialty Industrial Machinery',
  'ind_specialtyretail': 'Specialty Retail',
  'ind_staffingemploymentservices': 'Staffing & Employment Services',
  'ind_steel': 'Steel',
  'ind_telecomservices': 'Telecom Services',
  'ind_textilemanufacturing': 'Textile Manufacturing',
  'ind_thermalcoal': 'Thermal Coal',
  'ind_tobacco': 'Tobacco',
  'ind_toolsaccessories': 'Tools & Accessories',
  'ind_travelservices': 'Travel Services',
  'ind_trucking': 'Trucking',
  'ind_uranium': 'Uranium',
  'ind_utilitiesdiversified': 'Utilities - Diversified',
  'ind_utilitiesindependentpowerproducers': 'Utilities - Independent Power Producers',
  'ind_utilitiesregulatedelectric': 'Utilities - Regulated Electric',
  'ind_utilitiesregulatedgas': 'Utilities - Regulated Gas',
  'ind_utilitiesregulatedwater': 'Utilities - Regulated Water',
  'ind_utilitiesrenewable': 'Utilities - Renewable',
  'ind_wastemanagement': 'Waste Management',
}

const marketCapOption = {
  'cap_mega': 'Mega Cap (200 Billion or Greater)',
  'cap_large': 'Large Cap (10 Billion to 200 Billion)',
  'cap_mid': 'Mid Cap (2 Billion to 10 Billion)',
  'cap_small': 'Small Cap (300 Million to 2 Billion)',
  'cap_micro': 'Micro Cap (50 Million to 300 Million)',
  'cap_nano': 'Nano Cap (Under 50 Million)',
}

const dividendYieldOption = {
  'fa_div_none': 'None (0%)',
  'fa_div_pos': 'Positive (>0%)',
  'fa_div_high': 'High (>5%)',
  'fa_div_veryhigh': 'Very High (>10%)',
  'fa_div_o1': 'Over 1%',
  'fa_div_o2': 'Over 2%',
  'fa_div_o3': 'Over 3%',
  'fa_div_o4': 'Over 4%',
  'fa_div_o5': 'Over 5%',
  'fa_div_o6': 'Over 6%',
  'fa_div_o7': 'Over 7%',
  'fa_div_o8': 'Over 8%',
  'fa_div_o9': 'Over 9%',
  'fa_div_o10': 'Over 10%',
}

const trailingPEOption = {
  'fa_pe_low': 'Low (<15)',
  'fa_pe_profitable': 'Profitable (>0)',
  'fa_pe_high': 'High (>50)',
  'fa_pe_u5': 'Under 5',
  'fa_pe_u10': 'Under 10',
  'fa_pe_u15': 'Under 15',
  'fa_pe_u20': 'Under 20',
  'fa_pe_u25': 'Under 25',
  'fa_pe_u30': 'Under 30',
  'fa_pe_u35': 'Under 35',
  'fa_pe_u40': 'Under 40',
  'fa_pe_u45': 'Under 45',
  'fa_pe_u50': 'Under 50',
  'fa_pe_o5': 'Over 5',
  'fa_pe_o10': 'Over 10',
  'fa_pe_o15': 'Over 15',
  'fa_pe_o20': 'Over 20',
  'fa_pe_o25': 'Over 25',
  'fa_pe_o30': 'Over 30',
  'fa_pe_o35': 'Over 35',
  'fa_pe_o40': 'Over 40',
  'fa_pe_o45': 'Over 45',
  'fa_pe_o50': 'Over 50',
}

export { 
  sectorOption, 
  industryOption, 
  marketCapOption, 
  dividendYieldOption,
  trailingPEOption 
}