const dummyState = [
  {
    "symbol": "AAPL",
    "price": 116.97,
    "beta": 1.34325,
    "volAvg": 170959858,
    "mktCap": 2000479450000,
    "lastDiv": 0.7825,
    "range": "53.1525-137.98",
    "changes": 2,
    "companyName": "Apple Inc",
    "currency": "USD",
    "isin": "US0378331005",
    "cusip": "037833100",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Consumer Electronics",
    "website": "https://www.apple.com/",
    "description": "Apple, Inc. engages in the design, manufacture, and sale of smartphones, personal computers, tablets, wearables and accessories, and other variety of related services. The company is headquartered in Cupertino, California and currently employs 137,000 full-time employees. The company is considered one of the Big Four technology companies, alongside Amazon, Google, and Microsoft. The firm's hardware products include the iPhone smartphone, the iPad tablet computer, the Mac personal computer, the iPod portable media player, the Apple Watch smartwatch, the Apple TV digital media player, the AirPods wireless earbuds and the HomePod smart speaker. Apple's software includes the macOS, iOS, iPadOS, watchOS, and tvOS operating systems, the iTunes media player, the Safari web browser, the Shazam acoustic fingerprint utility, and the iLife and iWork creativity and productivity suites, as well as professional applications like Final Cut Pro, Logic Pro, and Xcode. Its online services include the iTunes Store, the iOS App Store, Mac App Store, Apple Music, Apple TV+, iMessage, and iCloud. Other services include Apple Store, Genius Bar, AppleCare, Apple Pay, Apple Pay Cash, and Apple Card.",
    "ceo": "Mr. Timothy Cook",
    "sector": "Technology",
    "country": "US",
    "fullTimeEmployees": "137000",
    "phone": "14089961010",
    "address": "1 Apple Park Way",
    "city": "Cupertino",
    "state": "CALIFORNIA",
    "zip": "95014",
    "dcfDiff": 89.92,
    "dcf": 123.667,
    "image": "https://financialmodelingprep.com/image-stock/AAPL.png",
    "ipoDate": "1980-12-12",
    "defaultImage": false
  },
  {
    "symbol": "ABBV",
    "price": 87.7,
    "beta": 0.68455,
    "volAvg": 6958086,
    "mktCap": 154775585000,
    "lastDiv": 4.5,
    "range": "62.55-101.28",
    "changes": 0.36,
    "companyName": "Abbvie Inc",
    "currency": "USD",
    "isin": "US00287Y1091",
    "cusip": "00287Y109",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Drug Manufacturers General",
    "website": "https://www.abbvie.com/",
    "description": "AbbVie, Inc. is a research-based biopharmaceutical company, which engages in the development and sale of pharmaceutical products. The company is headquartered in North Chicago, Illinois and currently employs 30,000 full-time employees. The firm is engaged in the discovery, development, manufacture and sale of a range of pharmaceutical products. Its products are focused on treating conditions, such as chronic autoimmune diseases in rheumatology, gastroenterology and dermatology; oncology, including blood cancers; virology, including hepatitis C virus (HCV) and human immunodeficiency virus (HIV); neurological disorders, such as Parkinson's disease and multiple sclerosis; metabolic diseases, including thyroid disease and complications associated with cystic fibrosis, and other serious health conditions. The company offers products in various categories, including HUMIRA (adalimumab), Oncology products, Virology Products, Additional Virology products, Metabolics/Hormones products, Endocrinology products and other products, which include Duopa and Duodopa (carbidopa and levodopa), Anesthesia products and ZINBRYTA (daclizumab).",
    "ceo": "Mr. Richard Gonzalez",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "30000",
    "phone": "18479327900",
    "address": "1 N Waukegan Rd",
    "city": "North Chicago",
    "state": "ILLINOIS",
    "zip": "60064",
    "dcfDiff": 45.83,
    "dcf": 112.793,
    "image": "https://financialmodelingprep.com/image-stock/ABBV.png",
    "ipoDate": "2013-01-02",
    "defaultImage": false
  },
  {
    "symbol": "ABT",
    "price": 109.65,
    "beta": 0.88871,
    "volAvg": 5320652,
    "mktCap": 194138620000,
    "lastDiv": 1.36,
    "range": "61.61-114.2",
    "changes": 1.11,
    "companyName": "Abbott Laboratories",
    "currency": "USD",
    "isin": "US0028241000",
    "cusip": "002824100",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Medical Devices",
    "website": "https://www.abbott.com",
    "description": "Abbott Laboratories engages in the discovery, development, manufacture, and sale of a broad and diversified line of health care products. The company is headquartered in Abbott Park, Illinois and currently employs 103,000 full-time employees. The firm operates through four segments: Established Pharmaceutical Products, Diagnostic Products, Nutritional Products and Vascular Products. Its Established Pharmaceutical Products include a range of branded generic pharmaceuticals manufactured around the world and marketed and sold outside the United States. Its Diagnostic Products include a range of diagnostic systems and tests. Its Nutritional Products include a range of pediatric and adult nutritional products. Its Company's Vascular Products include a range of coronary, endovascular, vessel closure and structural heart devices for the treatment of vascular disease. The Company, through St. Jude Medical, Inc., also offers products, such as rhythm management products, electrophysiology products, heart failure related products, vascular products, structural heart products and neuromodulation products.",
    "ceo": "Mr. Robert Ford",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "107000",
    "phone": "12246676100",
    "address": "100 Abbott Park Rd",
    "city": "ABBOTT PARK",
    "state": "ILLINOIS",
    "zip": "60064",
    "dcfDiff": -30.72,
    "dcf": 108.417,
    "image": "https://financialmodelingprep.com/image-stock/ABT.jpg",
    "ipoDate": "1937-03-01",
    "defaultImage": true
  },
  {
    "symbol": "AA",
    "price": 12.52,
    "beta": 2.34454,
    "volAvg": 5731101,
    "mktCap": 2327768580,
    "lastDiv": 0,
    "range": "5.16-23.465",
    "changes": -0.21,
    "companyName": "Alcoa Corp",
    "currency": "USD",
    "isin": "US0138721065",
    "cusip": "013872106",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Aluminum",
    "website": "https://www.alcoa.com/global/en/home.asp",
    "description": "Alcoa Corp. engages in the production of bauxite, alumina, and aluminum products. The company is headquartered in Pittsburgh, Pennsylvania and currently employs 14,000 full-time employees. The firm is engaged in the production and management of aluminum and alumina combined through its participation in various aspects of the industry, such as technology, mining, refining, smelting, and recycling. The firm's segments include Bauxite, Alumina, Aluminum, Cast Products, Energy and Rolled Products. The firm's Bauxite segment represents its global portfolio of bauxite mining assets. The firm's Alumina segment represents its refining system across the world, and processes bauxite into alumina and sells it directly to internal and external smelter customers across the world. The firm's Aluminum segment represents its smelter system across the world. Its Energy segment represents its portfolio of energy assets, with power production capacity of approximately 1,685 megawatts.",
    "ceo": "Mr. Roy Harvey",
    "sector": "Basic Materials",
    "country": "US",
    "fullTimeEmployees": "13800",
    "phone": "14123152900",
    "address": "201 Isabella St Ste 500",
    "city": "Pittsburgh",
    "state": "PENNSYLVANIA",
    "zip": "15212",
    "dcfDiff": -45.74,
    "dcf": 16.4214,
    "image": "https://financialmodelingprep.com/image-stock/AA.jpg",
    "ipoDate": "2016-10-18",
    "defaultImage": true
  },
  {
    "symbol": "ABEV",
    "price": 2.47,
    "beta": 0.563909,
    "volAvg": 27732310,
    "mktCap": 38379848000,
    "lastDiv": 0.117,
    "range": "1.9-4.81",
    "changes": 0.01,
    "companyName": "Ambev S.A. American Depositary Shares (Each representing 1)",
    "currency": "USD",
    "isin": null,
    "cusip": null,
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Beverages Brewers",
    "website": "http://www.ambev.com.br",
    "description": null,
    "ceo": "Mr. Jean Jereissati Neto",
    "sector": "Consumer Defensive",
    "country": "Brazil",
    "fullTimeEmployees": "50000",
    "phone": "55 11 2122 1414",
    "address": "Rua Dr. Renato Paes de Barros, 1017",
    "city": "Sao Paulo",
    "state": "SP",
    "zip": "04530-001",
    "dcfDiff": -7.2,
    "dcf": 0,
    "image": "https://financialmodelingprep.com/image-stock/ABEV.jpg",
    "ipoDate": null,
    "defaultImage": true
  },
  {
    "symbol": "AAL",
    "price": 13.2,
    "beta": 1.7035,
    "volAvg": 66639655,
    "mktCap": 6647691300,
    "lastDiv": 0.3,
    "range": "8.25-31.67",
    "changes": 0.045,
    "companyName": "American Airlines Group Inc",
    "currency": "USD",
    "isin": "US02376R1023",
    "cusip": "02376R102",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Airlines",
    "website": "https://www.aa.com/homePage.do?locale=en_US&pref=true",
    "description": "American Airlines Group, Inc. is a holding company, which engages in the operation of a network carrier through its principal wholly-owned mainline operating subsidiary, American. The company is headquartered in Fort Worth, Texas and currently employs 128,900 full-time employees. The firm's primary business activity is the operation of a network air carrier, providing scheduled air transportation for passengers and cargo. The firm operates through American segment, which provides air transportation for passengers and cargo. The firm's cargo division provides a range of freight and mail services with facilities and interline connections available across the globe. Together with its regional airline subsidiaries and third-party regional carriers operating as American Eagle, its airline operated an average of nearly 6,700 flights per day to nearly 350 destinations in more than 50 countries, principally from its hubs in Charlotte, Chicago, Dallas/Fort Worth, Los Angeles, Miami, New York, Philadelphia, Phoenix and Washington, District of Columbia, as of December 31, 2016. In the fiscal year ended December 31, 2016, approximately 199 million passengers boarded its mainline and regional flights.",
    "ceo": "Mr. William Parker",
    "sector": "Industrials",
    "country": "US",
    "fullTimeEmployees": "133000",
    "phone": "18179631234",
    "address": "1 Skyview Dr",
    "city": "Fort Worth",
    "state": "TEXAS",
    "zip": "76155",
    "dcfDiff": 193.71,
    "dcf": 13.1602,
    "image": "https://financialmodelingprep.com/image-stock/AAL.png",
    "ipoDate": "2013-12-09",
    "defaultImage": false
  },
  {
    "symbol": "A",
    "price": 105.76,
    "beta": 1.03676,
    "volAvg": 1320372,
    "mktCap": 32606867500,
    "lastDiv": 0.688,
    "range": "61.13-106.1",
    "changes": 1.6,
    "companyName": "Agilent Technologies Inc",
    "currency": "USD",
    "isin": "US00846U1016",
    "cusip": "00846U101",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Diagnostics & Research",
    "website": "https://www.agilent.com/",
    "description": "Agilent Technologies, Inc. engages in the provision of application focused solutions for life sciences, diagnostics, and applied chemical markets. The company is headquartered in Santa Clara, California and currently employs 16,300 full-time employees. The firm serves the life sciences, diagnostics and applied chemical markets. The company has three business segments: life sciences and applied markets business, diagnostics and genomics business, and Agilent CrossLab business. Its life sciences and applied markets business segment offers instruments and software that enable customers to identify, quantify and analyze the physical and biological properties of substances and products, as well as enable customers in the clinical and life sciences research areas to interrogate samples at the molecular level. Its diagnostics and genomics business segment includes the reagent partnership, pathology, companion diagnostics, genomics and the nucleic acid solutions businesses. Its Agilent CrossLab business segment spans the entire lab with its consumables and services portfolio.",
    "ceo": "Mr. Michael McMullen",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "16370",
    "phone": "14083458886",
    "address": "5301 Stevens Creek Blvd",
    "city": "Santa Clara",
    "state": "CALIFORNIA",
    "zip": "95051",
    "dcfDiff": -53.5,
    "dcf": 108.63,
    "image": "https://financialmodelingprep.com/image-stock/A.png",
    "ipoDate": "1999-11-18",
    "defaultImage": false
  },
  {
    "symbol": "ABB",
    "price": 26.85,
    "beta": 1.175382,
    "volAvg": 1748844,
    "mktCap": 56883872000,
    "lastDiv": 1.5710000000000002,
    "range": "14.71-26.945",
    "changes": 0.31,
    "companyName": "ABB Ltd",
    "currency": "USD",
    "isin": null,
    "cusip": null,
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Computer Hardware",
    "website": "http://www.abb.com",
    "description": null,
    "ceo": "Ulrich Spiesshofer",
    "sector": "Technology",
    "country": null,
    "fullTimeEmployees": null,
    "phone": null,
    "address": null,
    "city": null,
    "state": null,
    "zip": null,
    "dcfDiff": -1.38,
    "dcf": 19.12,
    "image": "https://financialmodelingprep.com/image-stock/ABB.jpg",
    "ipoDate": null,
    "defaultImage": true
  },
  {
    "symbol": "ACAD",
    "price": 42.73,
    "beta": 1.47579,
    "volAvg": 1431075,
    "mktCap": 6787874300,
    "lastDiv": 0,
    "range": "30.02-58.72",
    "changes": -0.45,
    "companyName": "ACADIA Pharmaceuticals Inc",
    "currency": "USD",
    "isin": "US0042251084",
    "cusip": "004225108",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Biotechnology",
    "website": "http://www.acadia-pharm.com/",
    "description": "ACADIA Pharmaceuticals, Inc. operates as a biopharmaceutical company focused on the development and commercialization of medicines to address unmet medical needs in central nervous system, or CNS, disorders. The company is headquartered in San Diego, California and currently employs 490 full-time employees. The firm is focused on the development and commercialization of medicines for central nervous system (CNS) disorders. Its lead drug candidate, NUPLAZID (pimavanserin), is used for the treatment of hallucinations and delusions associated with Parkinson's disease psychosis (PD Psychosis). NUPLAZID is a selective serotonin inverse agonist (SSIA), preferentially targeting 5-HT2A receptors. The firm is conducting a Phase II trial, referred to as the SERENE Study, designed to examine the efficacy and safety of pimavanserin as a treatment for Alzheimer's disease (AD) Agitation. The company is also conducting a Phase III, six-week, randomized, double-blind, placebo-controlled, multi-center, outpatient study, referred to as the ENHANCE-1 study, designed to examine the use of pimavanserin in patients with schizophrenia.",
    "ceo": "Mr. Stephen Davis",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "550",
    "phone": "18585582871",
    "address": "3611 Valley Centre Dr Ste 300",
    "city": "San Diego",
    "state": "CALIFORNIA",
    "zip": "92130",
    "dcfDiff": -24.29,
    "dcf": 42.9686,
    "image": "https://financialmodelingprep.com/image-stock/ACAD.jpg",
    "ipoDate": "2004-05-27",
    "defaultImage": true
  },
  {
    "symbol": "ABR",
    "price": 11.74,
    "beta": 1.9254,
    "volAvg": 1322373,
    "mktCap": 1317380610,
    "lastDiv": 1.19,
    "range": "3.54-15.77",
    "changes": -0.15,
    "companyName": "Arbor Realty Trust Inc",
    "currency": "USD",
    "isin": "US0389231087",
    "cusip": "038923108",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "REIT Mortgage",
    "website": "https://arbor.com/",
    "description": "Arbor Realty Trust, Inc. operates as real estate investment trust, which engages in the provision of loan origination and servicing for multifamily, seniors housing, healthcare, and diverse commercial real estate assets. The company is headquartered in Uniondale, New York and currently employs 468 full-time employees. The firm invests in a portfolio of structured finance assets in the multifamily and commercial real estate markets, primarily consisting of bridge and mezzanine loans, including junior participating interests in first mortgages, preferred and direct equity. Its segments include Structured Business and Agency Business. In addition, the Company may also directly acquire real property and invest in real estate-related notes and certain mortgage-related securities. The company focuses on investment types, such as Bridge Financing, Mezzanine Financing, Junior Participation Financing and Preferred Equity Investments. The company offers bridge financing products to borrowers, typically seeking short-term capital to use in an acquisition of property. The company offers mezzanine financing in the form of loans that are subordinate to a conventional first mortgage loan and senior to the borrower's equity in a transaction.",
    "ceo": "Mr. Ivan Kaufman",
    "sector": "Real Estate",
    "country": "US",
    "fullTimeEmployees": "532",
    "phone": "15165064200",
    "address": "333 Earle Ovington Blvd Ste 900",
    "city": "Uniondale",
    "state": "NEW YORK",
    "zip": "11553",
    "dcfDiff": null,
    "dcf": 13.2593,
    "image": "https://financialmodelingprep.com/image-stock/ABR.png",
    "ipoDate": "2004-04-07",
    "defaultImage": false
  },
  {
    "symbol": "ABC",
    "price": 96.86,
    "beta": 0.55116,
    "volAvg": 887253,
    "mktCap": 19773194200,
    "lastDiv": 1.64,
    "range": "72.06-106.45",
    "changes": -1.63,
    "companyName": "Amerisourcebergen Corp",
    "currency": "USD",
    "isin": "US03073E1055",
    "cusip": "03073E105",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Medical Distribution",
    "website": "",
    "description": "AmerisourceBergen Corp. engages provision of pharmaceutical products and business solutions that improve access to care. The company is headquartered in Chesterbrook, Pennsylvania and currently employs 22,000 full-time employees. The firm's segments include Pharmaceutical Distribution and Other. The firm provides services to healthcare providers, and pharmaceutical and biotech manufacturers. As of June 30, 2016, the Pharmaceutical Distribution segment consists of two operating segments, including the operations of AmerisourceBergen Drug Corporation (ABDC) and AmerisourceBergen Specialty Group (ABSG), which distributes specialty drugs to their customers. Servicing healthcare providers in the pharmaceutical supply channel, the Pharmaceutical Distribution segment's operations provide drug distribution and related services. The Other segment consists of the operations of various segments, including the AmerisourceBergen Consulting Services (ABCS), the World Courier Group, Inc. and the MWI Veterinary Supply, Inc. ABSG operates distribution facilities that focus primarily on complex disease treatment regimens.",
    "ceo": "Mr. Steven Collis",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "22000",
    "phone": "16107277000",
    "address": "1300 Morris Dr",
    "city": "Chesterbrook",
    "state": "PENNSYLVANIA",
    "zip": "19087",
    "dcfDiff": 60.11,
    "dcf": 111.558,
    "image": "https://financialmodelingprep.com/image-stock/ABC.jpg",
    "ipoDate": "1993-12-16",
    "defaultImage": true
  },
  {
    "symbol": "ABM",
    "price": 37.01,
    "beta": 1.26653,
    "volAvg": 396155,
    "mktCap": 2468089340,
    "lastDiv": 0.73,
    "range": "19.79-40.78",
    "changes": -0.47,
    "companyName": "ABM Industries Inc",
    "currency": "USD",
    "isin": "US0009571003",
    "cusip": "000957100",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Specialty Business Services",
    "website": "https://www.abm.com/",
    "description": "ABM Industries, Inc. engages in the provision of facility services for commercial, industrial, and institutional buildings. The company is headquartered in New York City, New York and currently employs 140,000 full-time employees. The firm operates through five segments: Janitorial, Facility Services, Parking, Building & Energy Solutions, and other. Its Janitorial segment provides a range of cleaning services for commercial office buildings, data centers, educational institutions, government buildings, health facilities, industrial buildings, retail stores, sport event facilities and transportation hubs. Its Facility Services segment provides onsite mechanical engineering and technical services and solutions relating to a range of facilities and infrastructure systems. Its Parking segment provides parking and transportation services. Its Building & Energy Solutions segment provides energy solutions; electrical; heating, ventilation and air conditioning; lighting, and other general maintenance and repair services for clients. Its other segment provides facility solutions to airlines and airports.",
    "ceo": "Mr. Scott Salmirs",
    "sector": "Industrials",
    "country": "US",
    "fullTimeEmployees": "140000",
    "phone": "12122970200",
    "address": "1 Liberty Plz Fl 7",
    "city": "New York City",
    "state": "NEW YORK",
    "zip": "10006",
    "dcfDiff": 60.49,
    "dcf": 37.7944,
    "image": "https://financialmodelingprep.com/image-stock/ABM.jpg",
    "ipoDate": "1971-11-08",
    "defaultImage": true
  },
  {
    "symbol": "ABEO",
    "price": 1.38,
    "beta": 1.4648,
    "volAvg": 1519290,
    "mktCap": 116993224,
    "lastDiv": 0,
    "range": "1.0-5.19",
    "changes": 0,
    "companyName": "Abeona Therapeutics Inc",
    "currency": "USD",
    "isin": "US00289Y1073",
    "cusip": "00289Y107",
    "exchange": "NASDAQ Capital Market",
    "exchangeShortName": "NASDAQ",
    "industry": "Biotechnology",
    "website": "https://abeonatherapeutics.com/",
    "description": "Abeona Therapeutics, Inc. is a clinical stage biopharmaceutical company, which engages in the development of gene therapy for severe and life threatening rare diseases. The company is headquartered in New York City, New York and currently employs 83 full-time employees. The Company’s lead programs include ABO-102 (AAV-SGSH), an adeno-associated virus (AAV) based gene therapy for Sanfilippo syndrome type A (MPS IIIA) and EB-101 (gene-corrected skin grafts) for recessive dystrophic epidermolysis bullosa (RDEB). The company is also developing ABO-101 (AAV-NAGLU) for Sanfilippo syndrome type B (MPS IIIB), ABO-201 (AAV-CLN3) gene therapy for juvenile Batten disease (JNCL), ABO-202 (AAV-CLN1) for treatment of infantile Batten disease (INCL), EB-201 for epidermolysis bullosa, ABO-301 (AAV-FANCC) for Fanconi anemia disorder and ABO-302 using a novel CRISPR/Cas9-based gene editing approach to gene therapy for rare blood diseases. The firm also has a plasma-based protein therapy pipeline, including alpha-1 protease inhibitor (SDF Alpha) for inherited COPD, using its proprietary Salt Diafiltration ethanol-free process.",
    "ceo": "DR. Joao Siffert",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "88",
    "phone": "16468134701",
    "address": "1330 Avenue of the Americas Fl 33",
    "city": "New York City",
    "state": "NEW YORK",
    "zip": "10019",
    "dcfDiff": null,
    "dcf": 3.78696,
    "image": "https://financialmodelingprep.com/image-stock/ABEO.png",
    "ipoDate": "1980-09-19",
    "defaultImage": false
  },
  {
    "symbol": "AAP",
    "price": 155.32,
    "beta": 1.4108,
    "volAvg": 797195,
    "mktCap": 10738638800,
    "lastDiv": 0.68,
    "range": "71.33-171.43",
    "changes": -2.34,
    "companyName": "Advance Auto Parts Inc",
    "currency": "USD",
    "isin": "US00751Y1064",
    "cusip": "00751Y106",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Specialty Retail",
    "website": "https://shop.advanceautoparts.com/",
    "description": "Advance Auto Parts, Inc. engages in the supply and distribution of aftermarket automotive products for both professional installers and do-it-yourself customers. The company is headquartered in Raleigh, North Carolina and currently employs 40,000 full-time employees. The firm's stores and branches offer a selection of brand name, original equipment manufacturer (OEM) and private label automotive replacement parts, accessories, batteries and maintenance items for domestic and imported cars, vans, sport utility vehicles and light and heavy duty trucks. The company serves through various channels ranging from traditional brick and mortar store locations to self-serving e-commerce sites. As of December 31, 2016, it operated 5,062 total stores and 127 branches primarily under the trade names Advance Auto Parts, Autopart International, Carquest and Worldpac. As of December 31, 2016, its Advance Auto Parts operations consisted of three geographic divisions, which included the operations of the stores operating under the Advance Auto Parts, Carquest and Autopart International trade names.",
    "ceo": "Mr. Thomas Greco",
    "sector": "Consumer Cyclical",
    "country": "US",
    "fullTimeEmployees": "39000",
    "phone": "15403624911",
    "address": "2635 E Millbrook Rd",
    "city": "Raleigh",
    "state": "NORTH CAROLINA",
    "zip": "27604",
    "dcfDiff": null,
    "dcf": 161.043,
    "image": "https://financialmodelingprep.com/image-stock/AAP.png",
    "ipoDate": "2001-11-29",
    "defaultImage": false
  },
  {
    "symbol": "AAXN",
    "price": 98.99,
    "beta": 0.53914,
    "volAvg": 620156,
    "mktCap": 6283449300,
    "lastDiv": 0,
    "range": "49.8-104.9",
    "changes": 1.92,
    "companyName": "Axon Enterprise Inc",
    "currency": "USD",
    "isin": "US05464C1018",
    "cusip": "05464C101",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Aerospace & Defense",
    "website": "https://www.axon.com/",
    "description": "Axon Enterprise, Inc. engages in the development, manufacturing, and sale of conducted electrical weapons for personal defense. The company is headquartered in Scottsdale, Arizona and currently employs 1,155 full-time employees. The company is also engaged in development of connected wearable on-officer cameras. The company operates through two segments: the sale of CEWs, accessories, and other related products and services (the TASER Weapons segment), and the Axon business, focused on devices, wearables, applications, cloud and mobile products (the Axon segment). Its TASER Weapons product line includes TASER X26P, TASER X2, TASER C2, TASER Pulse and Replacement Cartridges. Its hardware products include Axon Body 2, Axon Flex, Axon Fleet, Axon Interview, Axon Signal and Axon Dock. Its Axon software and mobile technologies include Evidence.com, Evidence.com for Prosecutors, Evidence Sync, Axon Capture, Axon View, Axon Five, Axon Convert and Axon Detect.",
    "ceo": "Mr. Patrick Smith",
    "sector": "Industrials",
    "country": "US",
    "fullTimeEmployees": "1323",
    "phone": "14809910797",
    "address": "17800 N 85th St",
    "city": "Scottsdale",
    "state": "ARIZONA",
    "zip": "85255",
    "dcfDiff": -40.42,
    "dcf": 96.09,
    "image": "https://financialmodelingprep.com/image-stock/AAXN.png",
    "ipoDate": "2001-05-08",
    "defaultImage": false
  },
  {
    "symbol": "AAXJ",
    "price": 80.12,
    "beta": 0,
    "volAvg": 1190643,
    "mktCap": 4582320000,
    "lastDiv": 1.1960000000000002,
    "range": "52.95-80.3",
    "changes": 0.47,
    "companyName": "iShares MSCI All Country Asia ex Japan Index Fund",
    "currency": "USD",
    "isin": null,
    "cusip": null,
    "exchange": "NASDAQ Global Market",
    "exchangeShortName": "NASDAQ",
    "industry": "",
    "website": "",
    "description": "AAXJ was created on 08/13/08 by Blackrock. The ETF tracks a market-cap weighted index of Asian stocks, excluding Japan. The fund holds securities from both developed and emerging markets in Asia.",
    "ceo": "None",
    "sector": "",
    "country": null,
    "fullTimeEmployees": null,
    "phone": "800-474-2737",
    "address": null,
    "city": null,
    "state": null,
    "zip": null,
    "dcfDiff": null,
    "dcf": 0,
    "image": "https://financialmodelingprep.com/image-stock/AAXJ.jpg",
    "ipoDate": "08/13/08",
    "defaultImage": true
  },
  {
    "symbol": "AAWW",
    "price": 67.73,
    "beta": 1.55094,
    "volAvg": 485850,
    "mktCap": 1770191360,
    "lastDiv": 0,
    "range": "14.97-68.63",
    "changes": 0.3,
    "companyName": "Atlas Air Worldwide Holdings Inc",
    "currency": "USD",
    "isin": "US0491642056",
    "cusip": "049164205",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Airports & Air Services",
    "website": "https://www.atlasair.com/",
    "description": "Atlas Air Worldwide Holdings, Inc. engages in the provision of outsourced aircraft and aviation operating services. The company is headquartered in Purchase, New York and currently employs 3,275 full-time employees. The firm provides outsourced aircraft and aviation operating services throughout the world, serving Africa, Asia, Australia, Europe, the Middle East, North America and South America through contractual service arrangements, including those through which it provides aircraft to customers and value-added services, including crew, maintenance and insurance (ACMI), as well as those through which it provides crew, maintenance and insurance, but not the aircraft (CMI); cargo and passenger charter services (Charter), and dry leasing aircraft and engines (Dry Leasing). The firm's segments include ACMI, Charter and Dry Leasing. The firm operates a fleet of about 749 freighters and provides customers a range of 747, 777, 767, 757 and 737 aircraft for domestic, regional and international cargo and passenger applications. Its subsidiaries include Atlas Air, Inc. (Atlas) and Southern Air, Inc. (Southern Air).",
    "ceo": "Mr. John Dietrich",
    "sector": "Industrials",
    "country": "US",
    "fullTimeEmployees": "3587",
    "phone": "19147018000",
    "address": "2000 Westchester Ave",
    "city": "Purchase",
    "state": "NEW YORK",
    "zip": "10577",
    "dcfDiff": 337.74,
    "dcf": 67.949,
    "image": "https://financialmodelingprep.com/image-stock/AAWW.png",
    "ipoDate": "1995-08-11",
    "defaultImage": false
  },
  {
    "symbol": "AAOI",
    "price": 11.83,
    "beta": 2.01416,
    "volAvg": 941441,
    "mktCap": 269416416,
    "lastDiv": 0,
    "range": "5.0-17.57",
    "changes": 0.24,
    "companyName": "Applied Optoelectronics Inc",
    "currency": "USD",
    "isin": "US03823U1025",
    "cusip": "03823U102",
    "exchange": "NASDAQ Global Market",
    "exchangeShortName": "NASDAQ",
    "industry": "Semiconductors",
    "website": "http://ao-inc.com/",
    "description": "Applied Optoelectronics, Inc. engages in the design and manufacture of optical communications products. The company is headquartered in Sugar Land, Texas and currently employs 2,956 full-time employees. The firm designs and manufactures a range of optical communications products at varying levels of integration, from components, subassemblies and modules to turnkey equipment. To Internet-based data center operators, it supplies optical transceivers that plug into switches and servers within the data center and allow these network devices to send and receive data over fiber optic cables. The firm supplies a range of products, including lasers, transmitters and transceivers, and turnkey equipment, to the CATV market. The firm designs, manufactures and integrates its own analog and digital lasers using a combination of Metal Organic Chemical Vapor Deposition (MOCVD) and its Molecular Beam Epitaxy (MBE) fabrication process.",
    "ceo": "Dr. Chih-Hsiang Lin",
    "sector": "Technology",
    "country": "US",
    "fullTimeEmployees": "3115",
    "phone": "12812951800",
    "address": "13139 Jess Pirtle Blvd",
    "city": "Sugar Land",
    "state": "TEXAS",
    "zip": "77478",
    "dcfDiff": 20.51,
    "dcf": 14.2016,
    "image": "https://financialmodelingprep.com/image-stock/AAOI.png",
    "ipoDate": "2013-09-26",
    "defaultImage": false
  },
  {
    "symbol": "AAN",
    "price": 58.67,
    "beta": 1.98995,
    "volAvg": 695878,
    "mktCap": 3939138820,
    "lastDiv": 0.155,
    "range": "13.01-78.65",
    "changes": -1.06,
    "companyName": "Aaron's Inc",
    "currency": "USD",
    "isin": "US0025353006",
    "cusip": "002535300",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Rental & Leasing Services",
    "website": "http://www.aarons.com",
    "description": "Aaron's, Inc. retails consumer electronics, computers, residential furniture, household appliances, and accessories. The company is headquartered in Atlanta, Georgia and currently employs 11,800 full-time employees. The firm engages in the sales and lease ownership and specialty retailing of furniture, consumer electronics, home appliances and accessories through its Company-operated and franchised stores in Canada, as well as its e-commerce platform, Aarons.com. Its segments include Sales and Lease Ownership, Progressive Finance Holdings, LLC (Progressive), Dent-A-Med, Inc., doing business as the HELPcard (DAMI), Franchise and Manufacturing. Its stores carry brands, such as Samsung, Frigidaire, Hewlett-Packard, LG, Whirlpool, Simmons, Philips, Ashley and Magnavox. As of December 31, 2016, it had 1,864 Aaron's stores, consisted of 1,165 Company-operated stores in 28 states, the District of Columbia and Canada, and 699 independently-owned franchised stores in 46 states and Canada. The company owns trademarks and trade names used in business, including Progressive, Dent-A-Med, the HELPcard and Woodhaven Furniture Industries.",
    "ceo": "Mr. John Robinson",
    "sector": "Industrials",
    "country": "US",
    "fullTimeEmployees": "12100",
    "phone": "16784023000",
    "address": "400 Galleria Pkwy SE Ste 300",
    "city": "Atlanta",
    "state": "GEORGIA",
    "zip": "30339-3182",
    "dcfDiff": 1669.03,
    "dcf": 58.4015,
    "image": "https://financialmodelingprep.com/image-stock/AAN.png",
    "ipoDate": "1982-11-05",
    "defaultImage": false
  },
  {
    "symbol": "ABMD",
    "price": 273.56,
    "beta": 1.39714,
    "volAvg": 326495,
    "mktCap": 12323139600,
    "lastDiv": 0,
    "range": "119.01-319.19",
    "changes": 2.36,
    "companyName": "ABIOMED Inc",
    "currency": "USD",
    "isin": "US0036541003",
    "cusip": "003654100",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Medical Devices",
    "website": "http://www.abiomed.com/",
    "description": "ABIOMED, Inc. engages in the research, development, and sale of medical devices to assist or replace the pumping function of the failing heart. The company is headquartered in Danvers, Massachusetts and currently employs 1,371 full-time employees. The firm offers care to heart failure patients. The firm operates in the segment of the research, development and sale of medical devices to assist or replace the pumping function of the failing heart. The firm develops, manufactures and markets products that are designed to enable the heart to rest, heal and recover by improving blood flow to the coronary arteries and end-organs and/or temporarily performing the pumping function of the heart. The firm's product portfolio includes the Impella 2.5, Impella CP, Impella RP, Impella LD, Impella 5.0 and AB5000. The firm's products are used in the cardiac catheterization lab (cath lab), by interventional cardiologists, the electrophysiology lab, the hybrid lab and in the heart surgery suite by heart surgeons.",
    "ceo": "Mr. Michael Minogue",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "1536",
    "phone": "19787775410",
    "address": "22 CHERRY HILL DR",
    "city": "Danvers",
    "state": "MASSACHUSETTS",
    "zip": "01923",
    "dcfDiff": 975.98,
    "dcf": 269.018,
    "image": "https://financialmodelingprep.com/image-stock/ABMD.png",
    "ipoDate": "1987-07-29",
    "defaultImage": false
  },
  {
    "symbol": "AAT",
    "price": 26.17,
    "beta": 0.94854,
    "volAvg": 301193,
    "mktCap": 1572134020,
    "lastDiv": 1.08,
    "range": "20.15-49.26",
    "changes": 0.39,
    "companyName": "American Assets Trust Inc",
    "currency": "USD",
    "isin": "US0240131047",
    "cusip": "024013104",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "REIT Diversified",
    "website": "https://www.americanassetstrust.com/",
    "description": "American Assets Trust, Inc. is a real estate investment trust. The company is headquartered in San Diego, California and currently employs 202 full-time employees. The firm owns, operates, acquires and develops retail, office, multifamily and mixed-use properties in Southern California, Northern California, Oregon, Washington, Texas and Hawaii markets. The firm operates in four business segments: retail, office, multifamily and mixed-use. As of December 31, 2016, the Company's portfolio consisted of 11 retail shopping centers; seven office properties; a mixed-use property consisting of a 369-room all-suite hotel and a retail shopping center, and five multifamily properties. Additionally, as of December 31, 2016, the Company owned land at four of its properties that it classified as held for development and construction in progress. The firm's markets include San Diego, the San Francisco Bay Area, Portland, Oregon, Bellevue, Washington and Oahu, Hawaii.",
    "ceo": "Mr. Ernest Rady",
    "sector": "Real Estate",
    "country": "US",
    "fullTimeEmployees": "205",
    "phone": "18583502600",
    "address": "11455 El Camino Real Ste 200",
    "city": "San Diego",
    "state": "CALIFORNIA",
    "zip": "92130",
    "dcfDiff": null,
    "dcf": 26.8129,
    "image": "https://financialmodelingprep.com/image-stock/AAT.jpg",
    "ipoDate": "2011-01-13",
    "defaultImage": true
  },
  {
    "symbol": "ABIO",
    "price": 4.38,
    "beta": 2.99805,
    "volAvg": 1107864,
    "mktCap": 40734000,
    "lastDiv": 0,
    "range": "2.21-22.0",
    "changes": 0,
    "companyName": "ARCA Biopharma Inc",
    "currency": "USD",
    "isin": "US00211Y5069",
    "cusip": "00211Y506",
    "exchange": "NASDAQ Capital Market",
    "exchangeShortName": "NASDAQ",
    "industry": "Biotechnology",
    "website": "http://arcabio.com/",
    "description": "ARCA biopharma, Inc. is a biopharmaceutical company, which develops genetically targeted therapies for heart failure and other cardiovascular diseases. The company is headquartered in Westminster, Colorado and currently employs 15 full-time employees. The firm is principally focused on developing genetically-targeted therapies for cardiovascular diseases. The firm's lead product candidate is Gencaro (bucindolol hydrochloride), a beta-blocker and mild vasodilator that the Company is evaluating in a clinical trial for the treatment of atrial fibrillation (AF) in patients with heart failure with reduced left ventricular ejection fraction (HFREF). Gencaro is considered part of the beta-blocker class of compounds because of its property of blocking both beta-1 and beta-2, receptors in the heart. The blocking of these receptors prevents the receptor from binding with other molecules, primarily the neurotransmitter norepinephrine (NE), which activate these receptors. The firm is conducting a Phase IIB/III clinical trial of Gencaro, known as GENETIC-AF.",
    "ceo": "Dr. Michael Bristow",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "9",
    "phone": "17209402200",
    "address": "11080 Circle Point Rd Ste 140",
    "city": "Westminster",
    "state": "COLORADO",
    "zip": "80020",
    "dcfDiff": -5.62,
    "dcf": 11.5097,
    "image": "https://financialmodelingprep.com/image-stock/ABIO.jpg",
    "ipoDate": "2000-07-21",
    "defaultImage": true
  },
  {
    "symbol": "ABUS",
    "price": 3.2,
    "beta": 3.028,
    "volAvg": 9056603,
    "mktCap": 269034560,
    "lastDiv": 0,
    "range": "0.82-9.02",
    "changes": 0.06,
    "companyName": "Arbutus Biopharma Corp",
    "currency": "USD",
    "isin": "CA03879J1003",
    "cusip": "03879J100",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Biotechnology",
    "website": "http://www.arbutusbio.com/",
    "description": "Arbutus Biopharma Corp. engages in discovering, developing and commercializing a cure for patients suffering from chronic Hepatitis B virus infection. The company is headquartered in Burnaby, British Columbia and currently employs 80 full-time employees. The firm is dedicated to discovering, developing and commercializing a cure for patients suffering from chronic hepatitis B infection, a disease of the liver caused by hepatitis B virus (HBV). The firm develops a portfolio of drug candidates with multiple mechanisms of action that results in a combination therapy to cure HBV. In addition to its HBV pipeline, the Company actively licenses its Lipid Nanoparticle (LNP) technology to its industry partners. This technology represents a delivery technology in RNA interference (RNAi) therapeutic development, which has enabled several clinical trials and has been administered to hundreds of human subjects.",
    "ceo": "Mr. William Collier",
    "sector": "Healthcare",
    "country": "US",
    "fullTimeEmployees": "80",
    "phone": "12674690914",
    "address": "701 Veterans Circle",
    "city": "Warminster",
    "state": "PENNSYLVANIA",
    "zip": "18974",
    "dcfDiff": -3628.13,
    "dcf": 3.62696,
    "image": "https://financialmodelingprep.com/image-stock/ABUS.png",
    "ipoDate": "2010-11-13",
    "defaultImage": false
  },
  {
    "symbol": "AB",
    "price": 30.26,
    "beta": 1.63501,
    "volAvg": 331530,
    "mktCap": 2915006460,
    "lastDiv": 2.68,
    "range": "13.24-36.06",
    "changes": 0.52,
    "companyName": "AllianceBernstein Holding LP",
    "currency": "USD",
    "isin": "US01881G1067",
    "cusip": "01881G106",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Asset Management",
    "website": "https://www.alliancebernstein.com",
    "description": "AllianceBernstein Holding LP engages in the provision of research, diversified investment management and related services. The company is headquartered in New York City, New York and currently employs 3,641 full-time employees. The firm offers a range of investment services, including equity strategies, with global and regional portfolios across capitalization ranges and investment strategies, including value, growth and equities; traditional and unconstrained fixed income strategies, including taxable and tax-exempt strategies; passive management, including index and enhanced index strategies; alternative investments, including hedge funds, fund of funds and private equity, and multi-asset solutions and services, including dynamic asset allocation, customized target-date funds and target-risk funds. The firm's services span various investment disciplines, including market capitalization, term and geographic locations.",
    "ceo": "Mr. Seth Bernstein",
    "sector": "Financial Services",
    "country": "US",
    "fullTimeEmployees": "3811",
    "phone": "12129691000",
    "address": "1345 Avenue of the Americas",
    "city": "New York City",
    "state": "NEW YORK",
    "zip": "10105",
    "dcfDiff": -29.57,
    "dcf": 27.62,
    "image": "https://financialmodelingprep.com/image-stock/AB.png",
    "ipoDate": "1988-04-15",
    "defaultImage": false
  },
  {
    "symbol": "ABG",
    "price": 114.7,
    "beta": 1.83906,
    "volAvg": 215264,
    "mktCap": 2212494080,
    "lastDiv": 0,
    "range": "39.36-123.45",
    "changes": -0.45,
    "companyName": "Asbury Automotive Group Inc",
    "currency": "USD",
    "isin": "US0434361046",
    "cusip": "043436104",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Auto & Truck Dealerships",
    "website": "https://www.asburyauto.com/",
    "description": "Asbury Automotive Group, Inc. operates as a holding company, which engages in the automotive dealership. The company is headquartered in Duluth, Georgia and currently employs 8,200 full-time employees. The firm owns and operates approximately 88 dealerships, consisting of 107 franchises, representing 31 domestic and foreign brands of vehicles. The company also operates approximately 25 collision repair centers. In addition, it owns and operates two standalone used vehicle stores in Florida. Its stores offer automotive products and services, including new and used vehicles; parts and service, including vehicle repair and maintenance services, replacement parts, and collision repair services; and finance and insurance products, including arranging vehicle financing through third parties and aftermarket products, such as extended service contracts, guaranteed asset protection (GAP) insurance, prepaid maintenance, and credit life and disability insurance. Its new vehicle revenues include new vehicle sales and lease transactions arranged by dealerships with third-party financial institutions.",
    "ceo": "Mr. David Hult",
    "sector": "Consumer Cyclical",
    "country": "US",
    "fullTimeEmployees": "8500",
    "phone": "17704188200",
    "address": "2905 Premiere Pkwy Ste 300",
    "city": "Duluth",
    "state": "GEORGIA",
    "zip": "30097",
    "dcfDiff": null,
    "dcf": 112.741,
    "image": "https://financialmodelingprep.com/image-stock/ABG.png",
    "ipoDate": "2002-03-14",
    "defaultImage": false
  },
  {
    "symbol": "AAON",
    "price": 63.56,
    "beta": 0.61866,
    "volAvg": 197441,
    "mktCap": 3321753600,
    "lastDiv": 0.35,
    "range": "40.48-64.305",
    "changes": 0.79,
    "companyName": "Aaon Inc",
    "currency": "USD",
    "isin": "US0003602069",
    "cusip": "000360206",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Building Products & Equipment",
    "website": "https://www.aaon.com/",
    "description": "AAON, Inc. engages in the engineering, manufacturing, marketing and sale of air conditioning and heating equipment. The company is headquartered in Tulsa, Oklahoma and currently employs 2,221 full-time employees. Its products serve the commercial and industrial new construction and replacement markets. Its rooftop and condensing unit markets consist of units installed on commercial or industrial structures of less than 10 stories in height. Its air handling units, self-contained units, geothermal/water-source heat pumps, chillers, packaged outdoor mechanical rooms and coils are applicable to all sizes of commercial and industrial buildings. The replacement market consists of products installed to replace existing units/components that are worn or damaged.",
    "ceo": "Mr. Norman Asbjornson",
    "sector": "Industrials",
    "country": "US",
    "fullTimeEmployees": "2290",
    "phone": "19185832266",
    "address": "2425 S Yukon Ave",
    "city": "Tulsa",
    "state": "OKLAHOMA",
    "zip": "74107",
    "dcfDiff": null,
    "dcf": 63.3891,
    "image": "https://financialmodelingprep.com/image-stock/AAON.png",
    "ipoDate": "1991-01-03",
    "defaultImage": false
  },
  {
    "symbol": "ABCB",
    "price": 25.88,
    "beta": 1.52616,
    "volAvg": 366993,
    "mktCap": 1798413950,
    "lastDiv": 0.6,
    "range": "17.12-44.9",
    "changes": -0.55,
    "companyName": "Ameris Bancorp",
    "currency": "USD",
    "isin": "US03076K1088",
    "cusip": "03076K108",
    "exchange": "Nasdaq Global Select",
    "exchangeShortName": "NASDAQ",
    "industry": "Banks Regional",
    "website": "https://www.amerisbank.com/",
    "description": "Ameris Bancorp is a bank holding company, which through the subsidiary, Ameris Bank, engages in the provision of banking services to its retail and commercial customers. The company is headquartered in Atlanta, Georgia and currently employs 2,906 full-time employees. The firm's business is conducted through its banking subsidiary, Ameris Bank (the Bank), which provides a range of banking services to its retail and commercial customers. The firm operates through four segments: the Banking Division, the Retail Mortgage Division, the Warehouse Lending Division and the SBA Division. The Banking Division is engaged in the delivery of financial services, which include commercial loans, consumer loans and deposit accounts. The Retail Mortgage Division is engaged in the origination, sales and servicing of one- to four-family residential mortgage loans. The Warehouse Lending Division is engaged in the origination and servicing of warehouse lines to other businesses that are secured by underlying one- to four-family residential mortgage loans. The SBA Division is engaged in the origination, sales and servicing of small business administration (SBA) loans.",
    "ceo": "Mr. Dennis Zember",
    "sector": "Financial Services",
    "country": "US",
    "fullTimeEmployees": "2679",
    "phone": "14046396500",
    "address": "3490 Piedmont Rd NE Ste 1550",
    "city": "Atlanta",
    "state": "GEORGIA",
    "zip": "30305",
    "dcfDiff": null,
    "dcf": 35.9892,
    "image": "https://financialmodelingprep.com/image-stock/ABCB.png",
    "ipoDate": "1994-05-19",
    "defaultImage": false
  },
  {
    "symbol": "ABTX",
    "price": 26.19,
    "beta": 1.27643,
    "volAvg": 54000,
    "mktCap": 535103616,
    "lastDiv": 0.2,
    "range": "20.88-38.95",
    "changes": 0.22,
    "companyName": "Allegiance Bancshares Inc",
    "currency": "USD",
    "isin": "US01748H1077",
    "cusip": "01748H107",
    "exchange": "NASDAQ Global Market",
    "exchangeShortName": "NASDAQ",
    "industry": "Banks Regional",
    "website": "http://ir.allegiancebank.com/",
    "description": "Allegiance Bancshares, Inc. operates as a bank holding company. The company is headquartered in Houston, Texas and currently employs 569 full-time employees. Through its subsidiary, Allegiance Bank (the Bank), the Company provides a range of commercial banking services primarily to Houston metropolitan area-based small to medium-sized businesses, professionals and individual customers. In addition to banking during normal business hours, the Company offers extended drive-in hours, automated teller machines (ATMs) and banking by telephone, mail and Internet. The firm also provides debit card services, cash management services and wire transfer services, and offers night depository, direct deposits, cashier's checks, letters of credit and mobile deposits. The company also offers safe deposit boxes, automated teller machines, drive-in services and round the clock depository facilities. The firm maintains an Internet banking Website that allows customers to obtain account balances and transfer funds among accounts.",
    "ceo": "Mr. Steven Retzloff",
    "sector": "Financial Services",
    "country": "US",
    "fullTimeEmployees": "587",
    "phone": "12818943200",
    "address": "8727 W Sam Houston Pkwy N",
    "city": "Houston",
    "state": "TEXAS",
    "zip": "77040",
    "dcfDiff": -36.81,
    "dcf": 41.0217,
    "image": "https://financialmodelingprep.com/image-stock/ABTX.png",
    "ipoDate": "2015-10-08",
    "defaultImage": false
  },
  {
    "symbol": "AC",
    "price": 34.52,
    "beta": 1.25129,
    "volAvg": 16672,
    "mktCap": 771925890,
    "lastDiv": 0.2,
    "range": "24.208956-65.13433",
    "changes": 0.41,
    "companyName": "Associated Capital Group Inc",
    "currency": "USD",
    "isin": "US0455281065",
    "cusip": "045528106",
    "exchange": "New York Stock Exchange",
    "exchangeShortName": "NYSE",
    "industry": "Capital Markets",
    "website": "http://www.associated-capital-group.com",
    "description": "Associated Capital Group, Inc. provides alternative investment management, institutional research and underwriting services. The company is headquartered in Greenwich, Connecticut and currently employs 62 full-time employees. The Company, through its subsidiaries, provides alternative investment management services and institutional research services, as well as management of its investment portfolio. The company operates through the investment advisory and asset management business segment. Gabelli & Company Investment Advisers, Inc. (GCIA) is a subsidiary of the Company. GCIA and its subsidiary, Gabelli & Partners, LLC (Gabelli & Partners), collectively serve as general partners, co-general partners or investment managers to investment funds, including limited partnerships and offshore companies (collectively, Investment Partnerships), and separate accounts. The company primarily manages assets in equity event-driven value strategies, across a range of risk and event arbitrage portfolios.",
    "ceo": "Mr. Douglas Jamieson",
    "sector": "Financial Services",
    "country": "US",
    "fullTimeEmployees": "39",
    "phone": "12036299595",
    "address": "191 Mason Street",
    "city": "Greenwich",
    "state": "CONNECTICUT",
    "zip": "10580",
    "dcfDiff": null,
    "dcf": 50.8231,
    "image": "https://financialmodelingprep.com/image-stock/AC.jpg",
    "ipoDate": "2015-11-09",
    "defaultImage": true
  },
  {
    "symbol": "AADR",
    "price": 57.99,
    "beta": 0,
    "volAvg": 4681,
    "mktCap": 109012500,
    "lastDiv": 0.314,
    "range": "33.75-59.1",
    "changes": 1.2101,
    "companyName": "AdvisorShares Dorsey Wright ADR",
    "currency": "USD",
    "isin": null,
    "cusip": null,
    "exchange": "NYSE Arca",
    "exchangeShortName": "NYSE",
    "industry": "",
    "website": "",
    "description": "AADR was created on 07/20/10 by AdvisorShares. The ETF is an actively managed ETF that aims to outperform the international market by holding ADRs with high Relative Strength.",
    "ceo": "None",
    "sector": "",
    "country": null,
    "fullTimeEmployees": null,
    "phone": "877-843-3831",
    "address": null,
    "city": null,
    "state": null,
    "zip": null,
    "dcfDiff": null,
    "dcf": 0,
    "image": "https://financialmodelingprep.com/image-stock/AADR.jpg",
    "ipoDate": "07/20/10",
    "defaultImage": true
  },
  {
    "symbol": "AAMC",
    "price": 20.4,
    "beta": 0.82715,
    "volAvg": 14595,
    "mktCap": 33295248,
    "lastDiv": 0,
    "range": "10.2-32.24",
    "changes": 0,
    "companyName": "Altisource Asset Management Corp",
    "currency": "USD",
    "isin": "VI02153X1080",
    "cusip": "02153X108",
    "exchange": "NYSE American",
    "exchangeShortName": "AMEX",
    "industry": "Asset Management",
    "website": "http://www.altisourceamc.com/",
    "description": "Altisource Asset Management Corp. engages in the provision of portfolio management and governance services to investment vehicles that acquire and own residential properties. The company employs 103 full-time employees The firm's primary client is Altisource Residential Corporation (Residential). The firm operates through segment, which is focused on providing asset management and certain corporate governance services to Residential. Its business strategy is to provide asset management services to Residential to generate cash available for distribution to its shareholders and thereby growing its earnings, and develop additional investment strategies and vehicles. Residential is a public real estate investment trust (REIT) that acquires and manages single-family rental properties by acquiring sub-performing and non-performing mortgage loans throughout the United States. In addition to providing services to Residential, it also provides management services to NewSource Reinsurance Company Ltd., which is an insurance and reinsurance company.",
    "ceo": "Mr. George Ellison",
    "sector": "Financial Services",
    "country": "VI",
    "fullTimeEmployees": "109",
    "phone": "13406921055",
    "address": "5100 Tamarind Reef",
    "city": "Christiansted",
    "state": "",
    "zip": "00820",
    "dcfDiff": null,
    "dcf": 32.957,
    "image": "https://financialmodelingprep.com/image-stock/AAMC.png",
    "ipoDate": "2012-12-11",
    "defaultImage": false
  },
  {
    "symbol": "AAME",
    "price": 2.01,
    "beta": 0.22096,
    "volAvg": 9981,
    "mktCap": 41112540,
    "lastDiv": 0.02,
    "range": "1.46-3.48",
    "changes": 0.01,
    "companyName": "Atlantic American Corp",
    "currency": "USD",
    "isin": "US0482091008",
    "cusip": "048209100",
    "exchange": "NASDAQ Global Market",
    "exchangeShortName": "NASDAQ",
    "industry": "Insurance Life",
    "website": "http://www.atlam.com/",
    "description": "Atlantic American Corp. is an insurance holding company, which engages in the life, health, and property and casualty insurance industries. The company is headquartered in Atlanta, Georgia and currently employs 155 full-time employees. The firm's principal operating subsidiaries are American Southern Insurance Company and American Safety Insurance Company (together known as American Southern) within the property and casualty insurance industry, and Bankers Fidelity Life Insurance Company and Bankers Fidelity Assurance Company (together known as Bankers Fidelity) within the life and health insurance industry. Each of American Southern and Bankers Fidelity is managed separately based upon the type of products it offers. American Southern's product lines include business automobile insurance policies, General Liability Insurance policies, Property Insurance policies and Surety Bonds. Products offered by Bankers Fidelity include ordinary and term life insurance, Medicare supplement and other accident and health insurance products.",
    "ceo": "Mr. Hilton Howell",
    "sector": "Financial Services",
    "country": "US",
    "fullTimeEmployees": "151",
    "phone": "14042665500",
    "address": "4370 Peachtree Rd Ne",
    "city": "Atlanta",
    "state": "GEORGIA",
    "zip": "30319",
    "dcfDiff": -2.45,
    "dcf": 2.60644,
    "image": "https://financialmodelingprep.com/image-stock/AAME.png",
    "ipoDate": "1980-01-16",
    "defaultImage": false
  },
  {
    "symbol": "AAU",
    "price": 0.845,
    "beta": 1.61631,
    "volAvg": 783050,
    "mktCap": 101651816,
    "lastDiv": 0,
    "range": "0.21-1.09",
    "changes": 0.068,
    "companyName": "Almaden Minerals Ltd",
    "currency": "CAD",
    "isin": "CA0202833053",
    "cusip": "020283305",
    "exchange": "NYSE American",
    "exchangeShortName": "AMEX",
    "industry": "Gold",
    "website": "http://www.almadenminerals.com/",
    "description": "Almaden Minerals Ltd. engages in the acquisition, exploration, and development of mineral properties. The company is headquartered in Vancouver, British Columbia and currently employs 16 full-time employees. The firm is engaged in the business of the acquisition of mineral properties. Its principal property interest includes the Tuligtic Property/Project-Mexico. The company has interest in ATW Resources Ltd. (ATW) that holds title in trust for the ATW project. The company holds an interest in the Logan property located in the Yukon Territory, Canada. The company has approximately two subsidiaries, including Puebla Holdings Inc., which is a holding company and Minera Gorrion, S.A. de C.V., which is an exploration company. Its Ixtaca deposit, the epithermal gold-silver target within the Tuligtic Property, is located approximately eight kilometers northwest of the town of San Francisco Ixtacamaxtitlan. The firm has not generated any revenues from its operations.",
    "ceo": "Dr. Morgan Poliquin",
    "sector": "Basic Materials",
    "country": "CA",
    "fullTimeEmployees": "12",
    "phone": "16046897644",
    "address": "1333 Johnston St Suite 210",
    "city": "Vancouver",
    "state": "BRITISH COLUMBIA",
    "zip": "V6H 3R9",
    "dcfDiff": null,
    "dcf": 0,
    "image": "https://financialmodelingprep.com/image-stock/AAU.jpg",
    "ipoDate": "1990-05-18",
    "defaultImage": true
  },
  {
    "symbol": "ACA",
    "price": 46.77,
    "beta": 0,
    "volAvg": 244640,
    "mktCap": 2260857090,
    "lastDiv": 0.2,
    "range": "28.14-48.64",
    "changes": 0.05,
    "companyName": "Arcosa Inc",
    "currency": "USD",
    "isin": "US0396531008",
    "cusip": "039653100",
    "exchange": "NYSE",
    "exchangeShortName": "NYSE",
    "industry": "Infrastructure Operations",
    "website": "https://www.arcosa.com/",
    "description": "Arcosa, Inc. engages in the provision of infrastructure-related products and services. The company is headquartered in Dallas, Texas and currently employs 5,889 full-time employees. The firm provides its products to a spectrum of markets throughout construction, energy, and transportation. The firm operates through three segments: Construction Products Group, Energy Equipment Group, and Transportation Products Group. The Construction Products Group segment produces and sells construction aggregates and manufactures and sells trench shields and shoring products and services for infrastructure-related projects. The Energy Equipment Group segment manufactures and sells products for energy-related businesses, including structural wind towers, steel utility structures for electricity transmission and distribution, and storage and distribution containers. The Transportation Products Group segment manufactures and sells products for the inland waterway and rail transportation industries including barges, barge-related products, axles, and couplers.",
    "ceo": "Mr. Antonio Carrillo",
    "sector": "Industrials",
    "country": "US",
    "fullTimeEmployees": "6275",
    "phone": "19729426500",
    "address": "500 N Akard St Ste 400",
    "city": "Dallas",
    "state": "TEXAS",
    "zip": "75201",
    "dcfDiff": null,
    "dcf": 50.5469,
    "image": "https://financialmodelingprep.com/image-stock/ACA.jpg",
    "ipoDate": "2018-10-16",
    "defaultImage": true
  },
  {
    "symbol": "ACB",
    "price": 5.03,
    "beta": 1.50249,
    "volAvg": 5355227,
    "mktCap": 608222590,
    "lastDiv": 0,
    "range": "4.32-47.28",
    "changes": -0.07,
    "companyName": "Aurora Cannabis Inc",
    "currency": "CAD",
    "isin": "CA05156X8843",
    "cusip": "05156X884",
    "exchange": "NYSE",
    "exchangeShortName": "NYSE",
    "industry": "Drug Manufacturers General Specialty & Generic",
    "website": "https://www.auroramj.com",
    "description": "Aurora Cannabis Inc is a Canada-based medical cannabis company. The Company’s principal strategic business lines are focused on the production, distribution and sale of cannabis in Canada and internationally. The Company is focused on offering its cannabis products to global medical cannabis market, consumer use cannabis market and global hemp-derived cannabidiol (CBD) markets. The Company offers varieties of cannabis infused products under various brands that includes Aurora, Aurora Drift, San Rafael '71, Daily Special, AltaVie, MedReleaf, CanniMed, Whistler and ROAR Sports. Its products portfolio includes dried cannabis, cannabis oil, soft-gels, oral dissolve strips, edibles, vaporizers and cannabis infused chocolates.",
    "ceo": "Mr. Michael Singer",
    "sector": "Healthcare",
    "country": "CA",
    "fullTimeEmployees": "3000",
    "phone": "16043625207",
    "address": "500-10355 Jasper Ave NW",
    "city": "Edmonton",
    "state": "ALBERTA",
    "zip": "T5J 1Y6",
    "dcfDiff": null,
    "dcf": 5.14606,
    "image": "https://financialmodelingprep.com/image-stock/ACB.png",
    "ipoDate": "2007-09-26",
    "defaultImage": false
  },
  {
    "symbol": "ACAM",
    "price": 10.2,
    "beta": 0,
    "volAvg": 134298,
    "mktCap": 389606336,
    "lastDiv": 0,
    "range": "9.5-10.5",
    "changes": -0.09,
    "companyName": "Acamar Partners Acquisition Corp",
    "currency": "USD",
    "isin": "US0042851024",
    "cusip": "004285102",
    "exchange": "NasdaqCM",
    "exchangeShortName": "NASDAQ",
    "industry": "Shell Companies",
    "website": "https://www.acamarpartners.com/",
    "description": "Acamar Partners Acquisition Corp is a blank check company. The Company is formed for the purpose of effecting a merger, capital stock exchange, asset acquisition, stock purchase, reorganization or similar business combination with one or more businesses. The Company’s target business is not limited to a particular industry or geographic region, but intends to acquire businesses in North America and Western Europe.",
    "ceo": "Mr. Luis Ignacio-Solrzano Aizpuru",
    "sector": "Financial Services",
    "country": "US",
    "fullTimeEmployees": "",
    "phone": "17862646680",
    "address": "1450 Brickell Ave Ste 2130, Miami",
    "city": "Miami",
    "state": "FLORIDA",
    "zip": "33131",
    "dcfDiff": null,
    "dcf": null,
    "image": "https://financialmodelingprep.com/image-stock/ACAM.jpg",
    "ipoDate": "2019-02-22",
    "defaultImage": true
  },
  {
    "symbol": "AAAU",
    "price": 19.22,
    "beta": 0,
    "volAvg": 633866,
    "mktCap": 0,
    "lastDiv": 0,
    "range": "14.43-20.63",
    "changes": 0.35,
    "companyName": "Perth Mint Physical Gold ETF",
    "currency": "USD",
    "isin": null,
    "cusip": null,
    "exchange": "NYSEArca",
    "exchangeShortName": "NYSE",
    "industry": "",
    "website": "",
    "description": "AAAU was created on 07/26/18 by Exchange Traded Concepts. The ETF tracks the gold spot price, less expenses and liabilities, using gold bars held in a vault in Perth, Australia. Investors can redeem their shares for gold coins and small bars.",
    "ceo": "None",
    "sector": "",
    "country": null,
    "fullTimeEmployees": null,
    "phone": "800-732-0330",
    "address": null,
    "city": null,
    "state": null,
    "zip": null,
    "dcfDiff": null,
    "dcf": null,
    "image": "https://financialmodelingprep.com/image-stock/AAAU.jpg",
    "ipoDate": "07/26/18",
    "defaultImage": true
  },
  {
    "symbol": "ABEQ",
    "price": 23.92,
    "beta": 0,
    "volAvg": 8503,
    "mktCap": 0,
    "lastDiv": 0,
    "range": "18.009-28.2",
    "changes": 0.05,
    "companyName": "Absolute Core Strategy ETF",
    "currency": "USD",
    "isin": null,
    "cusip": null,
    "exchange": "NYSEArca",
    "exchangeShortName": "NYSE",
    "industry": "",
    "website": "",
    "description": "ABEQ was created on 01/22/20 by Absolute Investment Advisers LLC. The ETF is an actively-managed portfolio of US stocks seeking positive absolute returns.",
    "ceo": "None",
    "sector": "",
    "country": null,
    "fullTimeEmployees": null,
    "phone": "833-267-3383",
    "address": null,
    "city": null,
    "state": null,
    "zip": null,
    "dcfDiff": null,
    "dcf": null,
    "image": "https://financialmodelingprep.com/image-stock/ABEQ.jpg",
    "ipoDate": "01/22/20",
    "defaultImage": true
  },
  {
    "symbol": "AACG",
    "price": 1.07,
    "beta": 1.71161,
    "volAvg": 59146,
    "mktCap": 33960088,
    "lastDiv": 0,
    "range": "0.61-1.92",
    "changes": -0.02,
    "companyName": "ATA Creativity Global",
    "currency": "CNY",
    "isin": "US00211V1061",
    "cusip": "00211V106",
    "exchange": "NasdaqGM",
    "exchangeShortName": "NASDAQ",
    "industry": "Education & Training Services",
    "website": "http://www.ata.net.cn",
    "description": "ATA Creativity Global engages in the provision of computer-based testing services. The company is headquartered in Beijing, Beijing and currently employs 101 full-time employees. The firm offers services for the creation and delivery of computer-based tests utilizing its test delivery platform, testing technologies and testing services in China. Its computer-based testing services are used for licensure and certification tests in various industries, including information technology (IT) services, banking, securities, teaching and insurance. The firm's computer-based testing services clients include professional associations, Chinese governmental agencies and state-owned enterprises. As of March 31, 2016, the Company's test center network included approximately 3,035 test centers located throughout China. Its network allows its clients to administer computer-based and paper-based tests. The firm has delivered approximately 88.1 million tests, including approximately 11.8 million free tests for business development purposes.",
    "ceo": "Mr. Cheng-Yaw Sun",
    "sector": "Consumer Defensive",
    "country": "CN",
    "fullTimeEmployees": "768",
    "phone": "861065181133",
    "address": "1/F East Gate, Building No.2, Jian Wai Soho,No.39 Dng Sn Hn Zhng Rd, Chao Yang District",
    "city": "Beijing",
    "state": "BEIJING",
    "zip": "100022",
    "dcfDiff": null,
    "dcf": 5.04595,
    "image": "https://financialmodelingprep.com/image-stock/AACG.jpg",
    "ipoDate": "2008-01-29",
    "defaultImage": true
  }
]

export default dummyState;